In [1]:

import sys
import os
from pathlib import Path

# Get the absolute path to the project root (adjust as needed)
# Set project root (adjust as needed)
project_root = Path(os.getcwd()).parent.parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

import pandas as pd
import logging
from core.data.collectors.factset_collector import FactSetCollector
from core.data.processors import PriceProcessor
from core.data.storage import ParquetHandler

# Configure logging
logging.basicConfig(level=logging.INFO)

## 1. Test Data Collection
Fetch data for Sector ETFs.

In [2]:
collector = FactSetCollector()
tickers = ['XLE','XLF','XLK','XLV','XLI','XLP','XLY','XLU','XLB','XLRE']
start_date = '2020-01-01'

print(f"Fetching data for: {tickers}")
df_raw = collector.fetch_history(tickers, start_date=start_date)

print("Raw Data Shape:", df_raw.shape)
df_raw.head()

INFO:core.data.collectors.factset_collector:Fetching OHLCV data for 10 tickers from 2020-01-01 to 2026-03-05
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe._data._data_source.__init__
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe._data._data_source.calculate
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe.dates._utils.get_dates

Fetching data for: ['XLE', 'XLF', 'XLK', 'XLV', 'XLI', 'XLP', 'XLY', 'XLU', 'XLB', 'XLRE']

INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe.universe._identifier_universe.__init__
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe.universe._identifier_universe.from_list
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe._data._data_source.__init__
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe._data._data_source.calculate
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe.screening._screen.__init__
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe._data._data_source.__init__
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe._data._data_source.calculate

Screen: 0it [00:00, ?it/s]

There were 1 warning(s) during the data fetch
* There are 1 dates in the future, 20260305

Generating DataFrame: 0it [00:00, ?it/s]

INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Dataframe of length: 16120 imported from QE using: 0 Factset Api Points
INFO:fds-fpe-package_fds.fpe._platform.logger_fds.clp.logger_helper:Executed function: fds.fpe.screening._screen._update

Raw Data Shape: (1612, 50)

               XLB                                       XLE                  \
             Close    High      Low    Open   Volume   Close    High     Low
date
2020-01-01  30.710  30.740  30.4350  30.480   0.0000  30.020  30.050  29.615
2020-01-02  30.350  30.970  30.3125  30.915  14.7149  30.290  30.335  30.115
2020-01-03  29.860  30.220  29.8500  30.040  24.8468  30.200  30.655  30.050
2020-01-06  29.730  29.915  29.7050  29.775  31.5287  30.435  30.590  30.200
2020-01-07  29.695  29.900  29.6000  29.680  40.5341  30.355  30.385  30.000

                             ...     XLV                                   \
              Open   Volume  ...   Close    High     Low    Open   Volume
date                         ...
2020-01-01  29.700   0.0000  ...  101.86  101.95  101.27  101.44  0.00000
2020-01-02  30.220  23.8939  ...  102.13  102.29  101.40  102.17  6.23652
2020-01-03  30.565  59.0312  ...  101.24  101.82  100.45  100.95  8.24745
2020-01-06  30.305  44.9214  ...  101.87  101.90  100.75  100.78  6.44176
2020-01-07  30.350  22.9868  ...  101.67  101.76  101.10  101.59  6.33649

               XLY
             Close    High     Low    Open   Volume
date
2020-01-01  62.710  62.740  62.425  62.515   0.0000
2020-01-02  63.455  63.455  62.860  63.105  12.5814
2020-01-03  62.915  63.100  62.610  62.650  11.1928
2020-01-06  63.090  63.105  62.375  62.455  12.8231
2020-01-07  62.990  63.135  62.725  63.050  18.3023

[5 rows x 50 columns]

## 2. Test Data Processing
Clean and process the data.

In [3]:
processor = PriceProcessor()
df_processed = processor.process(df_raw)

print("Processed Data Shape:", df_processed.shape)
df_processed.head()

Processed Data Shape: (1612, 50)

               XLB                                       XLE                  \
             Close    High      Low    Open   Volume   Close    High     Low
date
2020-01-01  30.710  30.740  30.4350  30.480   0.0000  30.020  30.050  29.615
2020-01-02  30.350  30.970  30.3125  30.915  14.7149  30.290  30.335  30.115
2020-01-03  29.860  30.220  29.8500  30.040  24.8468  30.200  30.655  30.050
2020-01-06  29.730  29.915  29.7050  29.775  31.5287  30.435  30.590  30.200
2020-01-07  29.695  29.900  29.6000  29.680  40.5341  30.355  30.385  30.000

                             ...     XLV                                   \
              Open   Volume  ...   Close    High     Low    Open   Volume
date                         ...
2020-01-01  29.700   0.0000  ...  101.86  101.95  101.27  101.44  0.00000
2020-01-02  30.220  23.8939  ...  102.13  102.29  101.40  102.17  6.23652
2020-01-03  30.565  59.0312  ...  101.24  101.82  100.45  100.95  8.24745
2020-01-06  30.305  44.9214  ...  101.87  101.90  100.75  100.78  6.44176
2020-01-07  30.350  22.9868  ...  101.67  101.76  101.10  101.59  6.33649

               XLY
             Close    High     Low    Open   Volume
date
2020-01-01  62.710  62.740  62.425  62.515   0.0000
2020-01-02  63.455  63.455  62.860  63.105  12.5814
2020-01-03  62.915  63.100  62.610  62.650  11.1928
2020-01-06  63.090  63.105  62.375  62.455  12.8231
2020-01-07  62.990  63.135  62.725  63.050  18.3023

[5 rows x 50 columns]

## 3. Test Data Storage
Save to Parquet and reload.

In [4]:
# Create a temporary storage directory
storage_path = project_root / 'data' / 'processed' / 'test'
handler = ParquetHandler(base_path=storage_path)

filename = 'sector_prices_test.parquet'
handler.save(df_processed, filename)

# Load it back
df_loaded = handler.load(filename)

print("Loaded Data Shape:", df_loaded.shape)
pd.testing.assert_frame_equal(df_processed, df_loaded)
print("Data integrity check passed!")

INFO:core.data.storage.parquet_handler:Saved data to /home/jovyan/QIS/data/processed/test/sector_prices_test.parquet

Loaded Data Shape: (1612, 50)
Data integrity check passed!

In [5]:
df_loaded

               XLB                                       XLE                  \
             Close    High      Low    Open   Volume   Close    High     Low
date
2020-01-01  30.710  30.740  30.4350  30.480   0.0000  30.020  30.050  29.615
2020-01-02  30.350  30.970  30.3125  30.915  14.7149  30.290  30.335  30.115
2020-01-03  29.860  30.220  29.8500  30.040  24.8468  30.200  30.655  30.050
2020-01-06  29.730  29.915  29.7050  29.775  31.5287  30.435  30.590  30.200
2020-01-07  29.695  29.900  29.6000  29.680  40.5341  30.355  30.385  30.000
...            ...     ...      ...     ...      ...     ...     ...     ...
2026-02-27  53.410  53.485  52.6700  52.860  12.1227  55.920  56.150  54.925
2026-03-02  53.250  53.385  52.5100  53.070  19.4446  57.040  57.880  56.270
2026-03-03  51.940  52.085  50.6900  51.670  27.3079  56.520  57.720  56.050
2026-03-04  51.920  52.380  51.6750  52.320  17.1418  56.190  56.430  55.325
2026-03-05  51.920  52.380  51.6750  52.320  17.1418  56.190  56.430  55.325

                              ...     XLV                                     \
              Open    Volume  ...   Close    High      Low    Open    Volume
date                          ...
2020-01-01  29.700    0.0000  ...  101.86  101.95  101.270  101.44   0.00000
2020-01-02  30.220   23.8939  ...  102.13  102.29  101.400  102.17   6.23652
2020-01-03  30.565   59.0312  ...  101.24  101.82  100.450  100.95   8.24745
2020-01-06  30.305   44.9214  ...  101.87  101.90  100.750  100.78   6.44176
2020-01-07  30.350   22.9868  ...  101.67  101.76  101.100  101.59   6.33649
...            ...       ...  ...     ...     ...      ...     ...       ...
2026-02-27  55.640   59.0715  ...  160.20  160.24  156.705  156.74  14.25010
2026-03-02  57.770  135.6330  ...  158.53  159.84  157.990  159.19  18.64140
2026-03-03  57.385  154.7710  ...  156.74  157.39  155.000  156.66  21.43260
2026-03-04  56.060   70.7327  ...  157.05  157.58  155.670  156.74  12.74570
2026-03-05  56.060   70.7327  ...  157.05  157.58  155.670  156.74  12.74570

                XLY
              Close     High      Low     Open   Volume
date
2020-01-01   62.710   62.740   62.425   62.515   0.0000
2020-01-02   63.455   63.455   62.860   63.105  12.5814
2020-01-03   62.915   63.100   62.610   62.650  11.1928
2020-01-06   63.090   63.105   62.375   62.455  12.8231
2020-01-07   62.990   63.135   62.725   63.050  18.3023
...             ...      ...      ...      ...      ...
2026-02-27  116.860  116.940  115.650  116.010   9.6362
2026-03-02  115.420  115.730  113.720  114.030  18.2058
2026-03-03  114.360  114.765  111.810  113.100  20.7731
2026-03-04  116.390  116.630  114.880  115.090  11.4967
2026-03-05  116.390  116.630  114.880  115.090  11.4967

[1612 rows x 50 columns]